### ISSUE TITLE
Label 'hacktoberfest-accepted' Needed?

### ISSUE THREAD

**Issue by f2010126** [Faiznurullah/Hacktoberfest-Contribution#83]
The contribution won't count unless the 'hacktoberfest-accepted' label is added as given here
https://hacktoberfest.digitalocean.com/

Could the maintainers please assign the label to the merged PRs? 
Thanks

**Comment by Faiznurullah** [comment]
Okay

Pada tanggal Min, 3 Okt 2021 12.14, Dipti Sengupta ***@***.***>
menulis:

**Comment by Faiznurullah** [comment]
Solved Brother Thank You

**Comment by Faiznurullah** [comment]
Please closed, thanks you
